# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    poor-vs-rich:
      - poor
      - rich
